### ISSUE TITLE
unable to install package

### ISSUE THREAD

**Issue by CJ1017** [Japrin/STARTRAC#1]
Hi,

I am trying to install the package per your guidelines, but I am having trouble installing certain sub packages due to the fact that I am running R3.6. I tried switching to the older version but I have still having issues installing the package.  Do you have any advice?

Thanks.

**Comment by Japrin** [comment]
Can you show me the error you encountered?  @CJ1017

**Comment by CJ1017** [comment]
Hi,

Here is the error I am receiving:

> devtools::install_github("Japrin/STARTRAC")
Downloading GitHub repo Japrin/STARTRAC@master
Skipping 1 packages not available: ComplexHeatmap
✔  checking for file ‘/private/var/folders/2n/d0vk2rw55rv9jlq9fznpp6z00000gn/T/RtmpPvgE5W/remotes1e67c93ef46/Japrin-STARTRAC-5176cfd/DESCRIPTION’ ...
─  preparing ‘Startrac’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘Startrac_0.1.0.tar.gz’
   
ERROR: dependency ‘ComplexHeatmap’ is not available for package ‘Startrac’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Startrac’
Error: Failed to install 'Startrac' from GitHub:
  (converted from warning) installation of package ‘/var/folders/2n/d0vk2rw55rv9jlq9fznpp6z00000gn/T//RtmpPvgE5W/file1e654421c8f/Startrac_0.1.0.tar.gz’ had non-zero exit status
> install.packages("ComplexHeatmap")
Warning in install.packages :
  package ‘ComplexHeatmap’ is not available (for R version 3.6.1)
> 


It stated that ComplexHeatmap is not available for package “Startrac” so I tried to install it separately but said it’s not available for R 3.6.1

Thank you,
Christina

**Comment by Japrin** [comment]
You can install ComplexHeatmap like this:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ComplexHeatmap")
```

**Comment by CJ1017** [comment]
Thank you! That worked. I was wondering, for the clone ID column of the input data, would it be ok to use the CDR3 instead?  I’m trying to convert my Seurat object to the needed input data for STARTRAC.

**Comment by Japrin** [comment]
Usually we define clonotype using both productive alpha/beta pairs (V gene, D gene, J gene, CDR3 nucleotide sequence). For a few cases, maybe two cells have the same CDR3, but there is some differences in nucleotide sequences.
