### ISSUE TITLE
what·s meaning of `loc`

### ISSUE THREAD

**Issue by SunYong0821** [Japrin/STARTRAC#10]
what·s meaning of `loc`?
where defined it

**Comment by Japrin** [comment]
`loc` means tissue-of-origin, such as Tumor, Blood etc. It is a column of your input data.

**Comment by SunYong0821** [comment]
> `loc` means tissue-of-origin, such as Tumor, Blood etc. It is a column of your input data.


Ileum Blood Cecum and etc may be ok？

**Comment by Japrin** [comment]
> > `loc` means tissue-of-origin, such as Tumor, Blood etc. It is a column of your input data.
> 
> Ileum Blood Cecum and etc may be ok？

It is OK.

**Comment by SunYong0821** [comment]
> > > `loc` means tissue-of-origin, such as Tumor, Blood etc. It is a column of your input data.
> > 
> > 
> > Ileum Blood Cecum and etc may be ok？
> 
> It is OK.

thx~
