### ISSUE TITLE
p.value is NA

### ISSUE THREAD

**Issue by lishashali** [Japrin/STARTRAC#2]
Hi, developer,

     I have followed the tutorial to run the sample data, but why the p-value in the Startrac.run-out is NA ?
   
![image](https://user-images.githubusercontent.com/54616730/89978279-c1f21500-dc9f-11ea-9831-d7a86594df7f.png)

Thanks a lot.

**Comment by Japrin** [comment]
Hi lisha,

Because it was ran in non-permutation model. Only ran with n.perm not NULL, p-values are calculated. But the permutation test is only experimental now.

Best Regards
